// The Jenkinsfile for the Linux Development Builds pipeline.
// This pipeline will build and test IDPS on a Linux OS.
// Refer to the README for more information on the Jenkins setup.

def AGENT_LABEL = "mini2p-3-build-node"
def BUILD_OS_TYPE = "linux"

def run_command(command, os) {
    // Run a command on a particular OS
    // On Windows, the command needs to be run as a Bat script
    // which calls the git bash shell. This was the best way to
    // run Unix commands on Windows using Jenkins
    if (os == "linux" || os == "mac") {
        sh command
    }
    else {
        bat ("sh -c \"${command}\"")
    }
}

pipeline {
    agent {
        label AGENT_LABEL
    }
    stages {
        stage("Setup") {
            steps {
                script {
                    checkout scm
                    run_command("make setup REMOTE_DIR=${IDPS_REMOTE_EXT_DIR} REMOTE_LOCAL_DIR=${IDPS_REMOTE_EXT_COPY_DIR}", BUILD_OS_TYPE)
                }
            }
        }
        stage("Build")
        {
            steps {
                script {
                    run_command("make build", BUILD_OS_TYPE)
                }
            }
        }
        stage("Test")
        {
            steps {
                script {
                    run_command("make test", BUILD_OS_TYPE)
                }
            }
        }
    }
    post {
        cleanup {
            cleanWs()
            dir("${env.WORKSPACE}@tmp") {
                deleteDir()
            }
        }
    }
}
