set(TARGET_NAME_CORE "isxcore")
set(CORE_MODULE_DIR ${CMAKE_CURRENT_LIST_DIR}/../../modules/core)
set(CORE_SRC_DIR ${CORE_MODULE_DIR}/src)
set(CORE_API_DIR ${CORE_MODULE_DIR}/api)
set(CORE_TEST_DIR ${CORE_MODULE_DIR}/test)
file(GLOB CORE_SRCS ${CORE_SRC_DIR}/*.cpp)
file(GLOB CORE_HDRS ${CORE_SRC_DIR}/*.h)
file(GLOB CORE_API_HDRS ${CORE_API_DIR}/*.h)

add_library(${TARGET_NAME_CORE} STATIC ${CORE_SRCS} ${CORE_HDRS} ${CORE_API_HDRS})

message("OPENCV: ${OPENCV_HEADER_SEARCH_PATHS}), ${OPENCV_LINK_LIBRARIES}")

target_include_directories(${TARGET_NAME_CORE} PUBLIC ${CORE_API_DIR} ${BOOST_HEADER_SEARCH_PATHS})
target_include_directories(${TARGET_NAME_CORE} PRIVATE
    ${QT_CORE_HEADER_SEARCH_PATHS}
    ${HDF5_HEADER_SEARCH_PATHS}
    ${JSON_HEADER_SEARCH_PATHS}
    ${FFMPEG_HEADER_SEARCH_PATHS}
    ${LIBTIFF_HEADER_SEARCH_PATHS}
    ${OPENCV_HEADER_SEARCH_PATHS})

set(MODULES_DEST_DIR ${CMAKE_BINARY_DIR}/../modules)
set(CORE_DEST_DIR ${MODULES_DEST_DIR}/lib)
set_target_properties(${TARGET_NAME_CORE} PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${CORE_DEST_DIR}
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${CORE_DEST_DIR}
    LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CORE_DEST_DIR}
    LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CORE_DEST_DIR}
    AUTOMOC ON
)

target_link_libraries(${TARGET_NAME_CORE} PRIVATE
    ${QT_CORE_LINK_LIBRARIES}
    ${HDF5_LINK_LIBRARIES}
    ${FFMPEG_LINK_LIBRARIES}
    ${LIBTIFF_LINK_LIBRARIES}
    ${OPENCV_LINK_LIBRARIES}
    ${BOOST_LINK_LIBRARIES}
)

setCommonCxxOptionsForTarget(${TARGET_NAME_CORE})
setOsDefinesForTarget(${TARGET_NAME_CORE})

# Pass the version info as compile options
target_compile_definitions(${TARGET_NAME_CORE} PRIVATE
    ISX_VERSION_MAJOR=${ISX_VERSION_MAJOR}
    ISX_VERSION_MINOR=${ISX_VERSION_MINOR}
    ISX_VERSION_PATCH=${ISX_VERSION_PATCH}
    ISX_VERSION_BUILD=${ISX_VERSION_BUILD}
    ISX_IS_BETA=${ISX_IS_BETA}
    ISX_IS_MINIMAL_API=${ISX_IS_MINIMAL_API})

# Install headers and third party shared libraries
installFiles(${TARGET_NAME_CORE} "${MODULES_DEST_DIR}/include/${TARGET_NAME_CORE}" "${CORE_API_HDRS}")
installQtCoreSharedLibs(${TARGET_NAME_CORE} "${MODULES_DEST_DIR}/third_party/${TARGET_NAME_CORE}")
installFfmpegSharedLibs(${TARGET_NAME_CORE} "${MODULES_DEST_DIR}/third_party/${TARGET_NAME_CORE}")
